baseURL = "https://santricyber.github.io/blog/"
languageCode = "id"
title = "SantriCyber Blog"
theme = "dream"

[params]
lightTheme = "emerald"
darkTheme = "forest"
author = "Syafmovic"
headerTitle = "SantriCyber"
siteStartYear = 2025

[author]
name = "Syafmovic"
homepage = "https://santricyber.github.io"

