baseURL = "https://santricyber.github.io/blog/"
languageCode = "en-us"
title = "SantriCyber Blog"
theme = "dream" # atau theme lainnya
paginate = 10
enableRobotsTXT = true

[author]
  name = "SantriCyber"
  email = "contact@santricyber.org"

[params]
  description = "Blog resmi SantriCyber"
  keywords = ["santri", "teknologi", "pemrograman", "blog"]

[menu]

  [[menu.main]]
    name = "Beranda"
    url = "/"
    weight = 1