baseURL = "https://santricyber.github.io/blog/"
DefaultContentLanguage = "id"
defaultContentLanguageInSubdir = false
languageCode = "id-ID"
title = "SantriCyber"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
enableGitInfo = false
summaryLength = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["post", "posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description = "Media belajar ngaji dan ngoding ala santri masa kini."
previewCardImagePlacement = "bottom"
showPostImage = false

[Params.Author]
  name = "SantriCyber"
  website = "https://santricyber.org"
  authorInfo = "Membangun masa depan dengan ngaji dan ngoding."
  authorPostImage = "/img/author-post-img.jpg"
  email = "contact@santricyber.org"
  facebook = "santricyber"
  instagram = "santricyber"
  youtube = "user/santricyber"
  twitter = "santricyber"
  linkedin = "santricyber"
  github = "SantriCyber"
  telegram = "santricyber"
  stackoverflow = "users/1234567/santricyber"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/blog/"
  weight = 3

[[menu.main]]
  name = "Collections"
  url = "/collections/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"