baseURL = "https://santricyber.github.io/blog/"
DefaultContentLanguage = "id"
defaultContentLanguageInSubdir = false
languageCode = "id-ID"
title = "SantriCyber"
theme = "lightbi"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
enableGitInfo = false
summaryLength = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["post", "posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description = "SantriCyber is a community for Santri and tech enthusiasts to share and learn about Islam, programming, cybersecurity, and technology. #SantriCyber.."
previewCardImagePlacement = "bottom"
showPostImage = false

[Params.Author]
  name = "SantriCyber"
  website = "https://santri.dev"
  authorInfo = "Share, Learn, Pray."
  authorPostImage = "/img/author-post-img.jpg"
  email = "staff@santri.dev"
  facebook = "santricyber.dev"
  instagram = "santricyber.dev"
  youtube = "user/santricyberdev"
  twitter = "santricyber"
  github = "SantriCyber"
  telegram = "santricyber"
  tiktok = "santricyber.dev"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Forums"
  url = "https://forum.santri.dev"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/blog/"
  weight = 3

[[menu.main]]
  name = "Collections"
  url = "/collections/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"