baseURL = "https://santricyber.github.io/blog/"
languageCode = "en-us"
title = "SantriCyber Blog"
theme = "lightbi"
paginate = 10
enableRobotsTXT = true

[params]
  description = "SantriCyber - Official"
  keywords = ["santri", "teknologi", "pemrograman", "blog"]

  [params.author]
    name = "SantriCyber"
    email = "staff@santri"

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/SantriCyber"
    icon = "github"

  [[params.social]]
    name = "X"
    url = "https://x.com/SantriCyber"
    icon = "twitter"

[menu]

  [[menu.main]]
    name = "Beranda"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Tentang"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Kontak"
    url = "/contact/"
    weight = 3