name: Sync Discourse to Hugo

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout script repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git
          pip3 install html2text requests python-frontmatter

      - name: Run Discourse to Hugo script
        env:
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
        run: |
          python3 discourseHugo.py